### ISSUE TITLE
Applikationscode implementieren

### ISSUE THREAD

**Issue by Alabamajack** [IOIOI/YASA#37]
Bitte anhand der RTE-Funktionen den Applikationscode schreiben(ist nicht viel) für folgende Komponenten:
- StartTrigger
- StopSensor
- SchussMotor
- Output 

für jede Runnable eine eigene Datei, wobei die Datei genauso heißt wie die Runnable an sich. 
macht euch selber aus wer was macht

**Comment by Litschi** [comment]
Is das schon gemacht?

**Comment by Alabamajack** [comment]
nö, kannste übernehmen
