### ISSUE TITLE
OSPort Funktionen implementieren

### ISSUE THREAD

**Issue by Alabamajack** [IOIOI/YASA#41]
Bitte alle RTE Funktionene ausimplementieren, die ein OSPort im Namen haben. Sinn dahinter ist klar. Es reicht was ganz einfaches(output auf display, taster,motoren). Dabei den Port jeweils über ein Makro definieren. Das Makro wird dann in der Codegenerierung gesetzt

**Comment by Litschi** [comment]
alle Funktionen haben zumindest eine Funktionalität implementiert, wenn noch mehr kommen muss, dann kommt das mit der Zeit
