### ISSUE TITLE
Rumkopieren ausmachen

### ISSUE THREAD

**Issue by Alabamajack** [IOIOI/YASA#47]
Besprechen wie was wohin kopiert wird(bei der Generierung). Einfachstes Mittel: Alles in eine Datei reinkopieren(evtl. noch mit mehr defines arbeiten). Dann müssen die anderen Dateien noch entsprechend geändert/verkürzt werden

**Comment by Philipp-E** [comment]
Kurze Zwischenfrage: Die impliziten Tasks für die Bluetoothkommunikation sind ja im Moment in einer extra Datei abgelegt, mit allen includes und allem zeuch. Wir haben ja etz ausgemacht, dass wir den Inhalt da rauskopieren und in diese eine Datei reinkopieren. Jetzt müsste man aber durch die ganze Datei iterieren und alles einzeln wo anders hinkopieren, sprich: Declare Task() nach oben, den Task an sich nach unten und die includes nach ganz oben in die Datei. Des is halt mega umständlich.
Was haltet ihr/du davon, den ganzen Spaß direkt ausm Quelltext in die Datei zu schreiben?

**Comment by Alabamajack** [comment]
Muss der ganze declare mist ganz oben stehen?
 
Außerdem: morgen oder reicht dir das nicht?

**Comment by Philipp-E** [comment]
Doch klar, kömma morgen in Ruhe ausmachen.

**Comment by Philipp-E** [comment]
Wir dürfen nicht vergessen, die Events, die wir zum Kommunizieren erzeugen auch den Tasks zuzuordnern, zu denen sie gehören (sprich: Bereits im oil File muss eingetragen werden, welche Events zu den Tasks gehören). Vllt können wir das morgen kurz in der Zwischenstunde besprechen, wenn ihr Bock habt.
