### ISSUE TITLE
Codegenerierung

### ISSUE THREAD

**Issue by Philipp-E** [IOIOI/YASA#48]
Hab hier in einem to do File bei mir schon seit einiger Zeit die Funktion void user_1ms_isr_type2(void) stehen.
So wie ich des sehe, müssen da dann auch irgendwelche Counter eingetragen werden, aber keinen Schimmer welche und weshalb.
Nachdem ich aber nichtmal weiß, ob wir die brauchen und was die macht, müssten wir das noch klären.

**Comment by Philipp-E** [comment]
Wir dürfen nicht vergessen, die Events, die wir zum Kommunizieren erzeugen auch den Tasks zuzuordnern, zu denen sie gehören (sprich: Bereits im oil File muss eingetragen werden, welche Events zu den Tasks gehören). Vllt können wir das morgen kurz in der Zwischenstunde besprechen, wenn ihr Bock habt.

**Comment by Alabamajack** [comment]
Erledigt
