### ISSUE TITLE
Comservice und BT-Handler nochmal überarbeiten

### ISSUE THREAD

**Issue by Alabamajack** [IOIOI/YASA#50]

**Comment by Gschmagee** [comment]
Wie funktioniert die Interbrickkommunikation, wie ruft der Commservice die Events auf? bzw wer ruft die Events der Funktionen auf

**Comment by Alabamajack** [comment]
ich weiß grad nicht was du meinst ;) ich schau mir gerade nochmals an :) sonst skype

**Comment by Philipp-E** [comment]
Wenn der Brick laut Konfiguration nich senden soll, dann muss das #define BT_DYNAMIC_WRITER_CODE TerminateTask; lauten. Im Moment ist das define leer, somit kommt kein User Task zum Zug.

Wenn der Brick laut Konfiguration nicht als Empfänger konfiguriert ist dann muss im Switch Case ein default: break; kommen. Im Moment steht nur eine leere Switch Anweisung(switch(id){}).

**Comment by Alabamajack** [comment]
geändert
